site_name: Mkdocs Multirepo Plugin Test

nav:
  - Home: 'index.md'
  - Testing: testing.md
  - DemoRepo: '!import https://github.com/jdoiro3/mkdocs-multirepo-demoRepo1?branch=main'

plugins:
  - multirepo